app:
  jwtExpirationInSec: 30240000
  jwtCmsExpirationInSec: 3600
  jwtSecret: JWTSuperSecretKey
server:
  port: 8080
spring:
  datasource:
    url: ${JAWSDB_URL:jdbc:mysql://127.0.0.1:3306/userroletest}
    username: root
    password: root
    tomcat:      validation-query: SELECT 1      test-while-idle: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
