app:
  jwtExpirationInSec: 30240000
  jwtCmsExpirationInSec: 3600
  jwtSecret: JWTSuperSecretKey
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userroletest
    username: root
    password: root
    validationQuery: SELECT 1
    testWhileIdle: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
